name: being_pupil
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  argon_buttons_flutter: ^1.1.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  dotted_border: ^2.0.0+2
  file_picker: ^4.3.0
  filter_list: ^1.0.0
  flutter_animation_progress_bar: ^2.0.1
  firebase_auth: ^3.3.4
  flutter_facebook_auth: ^3.5.7
  flutter_image_compress: ^1.1.0
  flutter_secure_storage: ^5.0.2
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.8
  google_sign_in: ^5.2.1
  image_picker: ^0.8.4+4
  page_transition: ^2.0.4
  path_provider: ^2.0.8
  persistent_bottom_nav_bar: ^4.0.2
  photo_view: ^0.13.0
  pin_code_fields: ^7.3.0
  place_picker: ^0.9.19-nullsafety #0.9.15
  pull_to_refresh: ^2.0.0
  readmore: ^2.1.0
  share: ^2.0.4
  shared_preferences: ^2.0.11
  sizer: ^2.0.15
  #syncfusion_flutter_datepicker: ^18.4.49-beta
  #textfield_tags: ^1.1.1
  webview_flutter: ^3.0.0
  #api_hit_app
  http: ^0.13.1
  google_fonts: ^2.1.0
  flutter_svg: ^1.0.0
  url_launcher: ^6.0.17
  #image_picker: ^0.6.7
  #dio: ^3.0.10 
  mime: ^1.0.1
  http_parser: ^4.0.0
  #wechat_assets_picker: ^6.2.4
  connectycube_sdk: ^2.0.7
  razorpay_flutter: ^1.2.7
  connectivity_plus: ^2.1.0
  the_apple_sign_in: ^1.1.1
  firebase_core: ^1.10.6
  jiffy: ^5.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/appLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/onBoard.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
